entity_print.settings:
  type: config_object
  label: 'Entity Print settings.'
  mapping:
    default_css:
      type: boolean
      label: 'Enable the default CSS.'
    force_download:
      type: boolean
      label: 'Force download of PDF'
    binary_location:
      type: string
      label: 'Location of the PDF engine binary.'
    pdf_engine:
      type: string
      label: 'The plugin id of the PDF engine to use.'

core.entity_view_display.*.*.*.third_party.entity_print:
  type: mapping
  label: 'Schema for Entity Print third party settings'
  mapping:
    label:
      type: string
      label: 'Label for view link'
